### PR TITLE
Set ignition endpoint at AgentClusterInstall creation

### PR DESCRIPTION
**Pull request by sjenning**
The `AgentClusterInstall` webhook prevents setting the ignition endpoint after the initial create.  The only code path for setting the ignition endpoint sets it after create which does not work.

https://github.com/openshift/cluster-api-provider-agent/blob/22297e732a690fce2485f723b4da9aed99f1bab1/controllers/agentcluster_controller.go#L118-L147

```
1.655390335604201e+09	ERROR	controller.agentcluster	Reconciler error	{"reconciler group": "capi-provider.agent-install.openshift.io", "reconciler kind": "AgentCluster", "name": "sjenning-example", "namespace": "clusters-sjenning-example", "error": "admission webhook \"agentclusterinstallvalidators.admission.agentinstall.openshift.io\" denied the request: Attempted to change AgentClusterInstall.Spec which is immutable after install started, except for ClusterMetadata fields. Unsupported change: \n\tIgnitionEndpoint: (<nil> => &{Url:https://ignition-server-clusters-sjenning-example.apps.ocp.variantweb.net/ CaCertificateReference:0xc0009aa240})"}
time="2022-06-16T14:49:50Z" level=info msg="Setting AgentClusterInstall" func="github.com/openshift/cluster-api-provider-agent/controllers.(*AgentClusterReconciler).ensureAgentClusterInstall" file="/workspace/controllers/agentcluster_controller.go:286" agent_cluster=sjenning-example agent_cluster_namespace=clusters-sjenning-example
```

We modified hypershift to wait until the ignition endpoint is known before creating the `AgentCluster`, but still need this fix.

https://bugzilla.redhat.com/show_bug.cgi?id=2097895
https://issues.redhat.com/browse/MGMTBUGSM-440

@enxebre @csrwng @eranco74 @avishayt

### CODE REVIEW

**Comment by sjenning** [comment]
Would also be good to figure out how the e2e is passing without this fix.  I took a quick look but it didn't jump out at me
https://github.com/openshift/assisted-test-infra/blob/0e8a8d85c9dec57d5b9bb1630ddd30a8f39ef8a0/src/tests/test_kube_api.py#L154-L224

**Comment by eranco74** [comment]
> Would also be good to figure out how the e2e is passing without this fix. I took a quick look but it didn't jump out at me https://github.com/openshift/assisted-test-infra/blob/0e8a8d85c9dec57d5b9bb1630ddd30a8f39ef8a0/src/tests/test_kube_api.py#L154-L224

Hmmm, you are right, I'm looking at the code and can't see how it can work with this webhook :confused:

**Comment by eranco74** [comment]
[logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-agent/49/pull-ci-openshift-cluster-api-provider-agent-master-e2e-capi-provider-hypershift/1539714153210449920/artifacts/e2e-capi-provider-hypershift/assisted-baremetal-gather/artifacts/clusters-test-infra-cluster-4a2f4d96/logs_capi-provider-74ffc47649-x8f9m_minikube.log) looks better.

**Review by eranco74 — COMMENTED** [review]
/approve
/lgtm

**Comment by eranco74** [comment]
This is the [log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-agent/47/pull-ci-openshift-cluster-api-provider-agent-master-e2e-capi-provider-hypershift/1536992213664272384/artifacts/e2e-capi-provider-hypershift/assisted-baremetal-gather/artifacts/clusters-test-infra-cluster-9ee9f6b2/logs_capi-provider-6f698f6b59-ljzqf_minikube.log) from a previous PR job running without these changes
Unsure why the webhook didn't block the change there :man_shrugging:

**Comment by eranco74** [comment]
In any case, I think we can allow to update the ACI once the installation is complete
https://issues.redhat.com/browse/MGMT-10915

**Pull request merged**
