### PR TITLE
MGMT-14838: Move CAPI APIs from v1alpha1 to v1beta1

### PR DESCRIPTION
**Pull request by CrystalChun**
https://issues.redhat.com/browse/MGMT-14838
/cc @eranco74 @filanov

### CODE REVIEW

**Comment by CrystalChun** [comment]
`ci/prow/e2e-ai-operator-ztp-capi` fails because it uses `hypershift install` to install the CAPI APIs (see non-flaky job [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-agent/82/pull-ci-openshift-cluster-api-provider-agent-master-e2e-ai-operator-ztp-capi/1700272054315520000)) 

But hypershift uses our API folder in their vendor directory to generate CRDs that it applies during the `hypershift install` cmd ([src](https://github.com/openshift/hypershift/commit/3fef5f7461e1763ae641cb3ceeea3260a98361f5#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R129-R133))

Should we create a PR in hypershift and manually add the new CRD versions or should we merge this first then create the PR in hypershift?

**Comment by eranco74** [comment]
> `ci/prow/e2e-ai-operator-ztp-capi` fails because it uses `hypershift install` to install the CAPI APIs (see non-flaky job [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-api-provider-agent/82/pull-ci-openshift-cluster-api-provider-agent-master-e2e-ai-operator-ztp-capi/1700272054315520000))
> 
> But hypershift uses our API folder in their vendor directory to generate CRDs that it applies during the `hypershift install` cmd ([src](https://github.com/openshift/hypershift/commit/3fef5f7461e1763ae641cb3ceeea3260a98361f5#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R129-R133))
> 
> Should we create a PR in hypershift and manually add the new CRD versions or should we merge this first then create the PR in hypershift?

Let's merge and update hypershift later

**Comment by eranco74** [comment]
/override ci/prow/e2e-ai-operator-ztp-capi 
The test is expected to fail due to api version update

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Pull request merged**
